### ISSUE TITLE
IO Expander, limiting I2C clock frequency?

### ISSUE THREAD

**Issue by MrMap** [iNavFlight/hardware#1]
Hi,

I think it´s a great idea with this IO expander and I consider to obtain one to play with inside the iNav eco system
But - I read the PCF8574A data sheet, 100 kHz is max I2C clock frequency. As I understand it, in general the recommendation is to set the FC I2C bus frequency as high as possible, today I use 800 kHz with a F675 board. 

Is it correct that I would have to change from 800 to 100 kHz to get them working together (the FC and the IO expander?).

**Comment by DzikuVx** [comment]
@MrMap I have tested it with 400kHz and 800kHz without any problems. There was no need for extra pullups

**Comment by MrMap** [comment]
Ok, that´s great!
So i guess now I have no excuse but to buy one :D
Thank you for prompt reply, Pawel.
